#parameters:

services:
# Factory
    oka_pagination.default.object_manager:
        class: Doctrine\Common\Persistence\ObjectManager
        public: false

#    oka_pagination.entity_manager:
#        class: Doctrine\Common\Persistence\ObjectManager
#        factory: [ "@doctrine", getManager ]
#        arguments: [ "%oka_pagination.model_manager_name%" ]
#        public: false

# Services
    oka_pagination.bag:
        class: Oka\PaginationBundle\Service\PaginationBag
        arguments: [[]]
        public: false

#, "@twig"
    oka_pagination.manager:
        class: Oka\PaginationBundle\Service\PaginationManager
        arguments: [ "@service_container", "@oka_pagination.default.object_manager", "@oka_pagination.bag", "%oka_pagination.item_per_page%", "%oka_pagination.max_page_number%", "%oka_pagination.template%" ]
        tags:
          - { name: twig.extension }