services:
#Factory
    oka_pagination.default.object_manager:
        class: Doctrine\Common\Persistence\ObjectManager

#Services
    oka_pagination.manager_bag:
        public: false
        class: Oka\PaginationBundle\Service\PaginationManagerBag
        arguments: [[]]

    oka_pagination.manager:
        public: true
        class: Oka\PaginationBundle\Service\PaginationManager
        arguments: [ '@service_container', '@oka_pagination.manager_bag', '@oka_pagination.query_builder_handler', '%oka_pagination.item_per_page%', '%oka_pagination.max_page_number%', '%oka_pagination.template%', '%oka_pagination.request%' ]

    oka_pagination.query_builder_handler:
        public: true
        class: Oka\PaginationBundle\Service\QueryBuilderHandler
        arguments: [[]]

    oka_pagination.query_builder_manipulator:
        alias: 'oka_pagination.query_builder_handler'
        public: true
